# Generated by Django 5.2.5 on 2025-10-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=10)),
                ('Estado', models.BooleanField(default=True)),
                ('Horas', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Combustible', models.CharField(max_length=45)),
                ('Fecha_Recarga', models.CharField(max_length=10)),
                ('Lugar', models.CharField(max_length=55)),
                ('Encargado', models.CharField(max_length=40)),
                ('Cantidad_Estanque', models.CharField(max_length=40)),
                ('Recargar', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Mantencion', models.CharField(max_length=50)),
                ('Fecha_Mantencion', models.CharField(max_length=20)),
            ],
        ),
    ]
