# Generated by Django 5.2.5 on 2025-11-03 15:00

import AppFlota.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username solo puede contener letras, números, guiones y underscores', regex='^[a-zA-Z0-9_-]+$')])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener al menos 8 caracteres', regex='^.{8,}$')])),
                ('nombre', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Formato de email inválido', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('cargo', models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer'), ('mecanico', 'Mecánico')], max_length=20)),
            ],
            options={
                'db_table': 'appflota_usuario',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('ID_Tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFlota.usuario')),
                ('RUTChofer', AppFlota.models.RUTField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9 o 12345678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9kK]$|^\\d{7,8}-[0-9kK]$')])),
                ('Nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('Fecha_Nacimiento', models.DateField(validators=[AppFlota.models.NoFechaFuturaValidator(), AppFlota.models.EdadMinimaValidator(21), AppFlota.models.EdadMaximaValidator(75)])),
                ('Telefono', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener 9 dígitos comenzando con 9', regex='^\\+56 9 \\d{4} \\d{4}$|^9\\d{8}$')])),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones'), ('Licencia', 'Licencia'), ('Suspendido', 'Suspendido')], max_length=45)),
                ('Horas', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Horas debe ser un número entre 0 y 999', regex='^\\d{1,3}$')])),
                ('Email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppFlota.usuario')),
                ('RUT_Mecanico', AppFlota.models.RUTField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9 o 12345678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9kK]$|^\\d{7,8}-[0-9kK]$')])),
                ('Nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('Fecha_Nacimiento', models.DateField(validators=[AppFlota.models.NoFechaFuturaValidator(), AppFlota.models.EdadMinimaValidator(18), AppFlota.models.EdadMaximaValidator(80)])),
                ('Telefono', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener 9 dígitos comenzando con 9 o formato +56 9 XXXX XXXX', regex='^\\+56 9 \\d{4} \\d{4}$|^9\\d{8}$')])),
                ('Email', models.CharField(max_length=45)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones'), ('Licencia', 'Licencia')], max_length=45)),
                ('Taller', models.CharField(max_length=45)),
                ('Horas', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Horas debe ser un número entre 0 y 999', regex='^\\d{1,3}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de patente invalido. Use: AA1234 o AB1234CD', regex='^[A-Z]{2}\\d{4}$|^[A-Z]{2}\\d{3}[A-Z]{2}$')])),
                ('VIN', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='VIN debe tener 17 caracteres alfanuméricos (excluyendo I, O, Q)', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('motor', models.CharField(max_length=50)),
                ('seguro', models.BooleanField(default=True)),
                ('revision_tecnica', models.BooleanField(default=True)),
                ('permiso_circulacion', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=True)),
                ('kilometraje', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000, message='Kilometraje no puede superar 1,000,000 km')])),
                ('estanque', models.DecimalField(decimal_places=2, help_text='Capacidad en litros', max_digits=5, validators=[django.core.validators.MinValueValidator(1, message='Capacidad mínima: 1 litro'), django.core.validators.MaxValueValidator(500, message='Capacidad máxima: 500 litros')])),
                ('tonelaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Tonelaje mínimo: 0.1 toneladas'), django.core.validators.MaxValueValidator(100, message='Tonelaje máximo: 100 toneladas')])),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='AppFlota.tipovehiculo')),
                ('chofer_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to='AppFlota.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Combustible', models.CharField(choices=[('93', '93'), ('95', '95'), ('97', '97'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('GLP', 'GLP')], max_length=45)),
                ('Fecha_Recarga', models.DateField()),
                ('Lugar', models.CharField(max_length=45)),
                ('Encargado', models.CharField(max_length=45)),
                ('Cantidad_Estanque', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1, message='Cantidad mínima: 0.1 litros'), django.core.validators.MaxValueValidator(500, message='Cantidad máxima: 500 litros')])),
                ('Recargar', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas_combustible', to='AppFlota.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('ID_Mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Mantencion', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Correctiva', 'Correctiva'), ('Predictiva', 'Predictiva'), ('Programada', 'Programada')], max_length=45)),
                ('Fecha', models.DateField()),
                ('Lugar', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='La descripción debe tener al menos 10 caracteres', regex='^.{10,}$')])),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='AppFlota.vehiculo')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_realizados', to='AppFlota.mecanico')),
            ],
        ),
    ]
