# Generated by Django 5.2.6 on 2025-10-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('RUTChofer', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Fecha_Nacimiento', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('Horas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Combustible', models.CharField(max_length=45)),
                ('Fecha_Recarga', models.CharField(max_length=45)),
                ('Lugar', models.CharField(max_length=45)),
                ('Encargado', models.CharField(max_length=45)),
                ('Cantidad_Estanque', models.CharField(max_length=45)),
                ('Recargar', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('ID_Mantencion', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo_Mantencion', models.CharField(max_length=45)),
                ('Fecha', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('RUT_Mecanico', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Fecha_Nacimiento', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('Taller', models.CharField(max_length=45)),
                ('Horas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('ID_Tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Cargo', models.CharField(max_length=45)),
                ('Contraseña', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('VIN', models.CharField(max_length=17)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=4)),
                ('motor', models.CharField(max_length=50)),
                ('seguro', models.BooleanField(default=True)),
                ('revision_tecnica', models.BooleanField(default=True)),
                ('permiso_circulacion', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=True)),
                ('kilometraje', models.PositiveBigIntegerField(default=0)),
                ('estanque', models.DecimalField(decimal_places=2, help_text='Capacidad en litros', max_digits=5)),
                ('tonelaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asignacion', models.CharField(max_length=50)),
            ],
        ),
    ]
