# Generated by Django 5.2.5 on 2025-11-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustible',
            name='Encargado',
        ),
    ]
