# Generated by Django 4.2.8 on 2025-11-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlota', '0002_remove_combustible_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='Email',
        ),
    ]
