# Generated by Django 4.2.24 on 2025-11-09 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlota', '0005_alter_usuario_options_alter_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='Telefono',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener 9 dígitos comenzando con 9 o formato +56 9 XXXX XXXX', regex='^\\+56 9 \\d{4} \\d{4}$|^9\\d{8}$|^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer'), ('mecanico', 'Mecánico')], default='chofer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido. Use: ABCD12 (4 letras + 2 números)', regex='^[A-Z]{4}\\d{2}$')]),
        ),
    ]
